version: '3.8'

services:
  # Backend API service
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    container_name: churn-prediction-api
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=backend/app.py
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///churn_prediction.db
    volumes:
      - ./data:/app/data
      - ./models:/app/models
    networks:
      - churn-network

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: docker/Dockerfile.frontend
      args:
        - REACT_APP_API_URL=http://localhost:5000
    container_name: churn-prediction-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - churn-network

networks:
  churn-network:
    driver: bridge 